name: pull-request-ci
on: [push, pull_request]
jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install system build dependencies
        run: >
          sudo apt-get update &&
          sudo apt-get install libsystemd-dev ninja-build

      - name: Install meson
        run: pip install --user meson

      - name: Install python dependencies for mctp tests
        run: pip install --user -r tests/requirements.txt

      - name: Configure mctp build
        run: meson setup build -Db_sanitize=address

      - name: Build mctp
        run: meson compile -C build

      - name: Check formatting
        run: ninja -C build clang-format-check

      - name: Test mctp
        run: meson test -C build --verbose

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: default-meson-testlog
          path: build/meson-logs/testlog.txt

  no-libsystemd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install system build dependencies
        run: >
          sudo apt-get update &&
          sudo apt-get install ninja-build

      - name: Install meson
        run: pip install --user meson

      - name: Install python dependencies for mctp tests
        run: pip install --user -r tests/requirements.txt

      - name: Configure mctp build
        run: meson setup build -Db_sanitize=address

      - name: Build mctp
        run: meson compile -C build

      - name: Test mctp
        run: meson test -C build --verbose

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: no-libsystemd-meson-testlog
          path: build/meson-logs/testlog.txt
